Style/Rule1:
  Description: Desc 1
  Enabled: false
Style/Rule2:
  Description: Desc 2
  Enabled: true
Style/Rule3:
  Description: Desc 3
  Enabled: true
Style/Rule4:
  Description: Desc 4
  Enabled: true
