#!/usr/bin/env ruby
lib = File.expand_path(File.dirname(__FILE__) + "/../lib")
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require "commander"
require "hound"
require "hound/cli"

Hound::Cli.new.run
